/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMyDashboardRouteImport } from './routes/_app/my-dashboard'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDailyReportRouteImport } from './routes/_app/daily-report'
import { Route as AppCreateTenantRouteImport } from './routes/_app/create-tenant'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppTeamRouteRouteImport } from './routes/_app/team/route'
import { Route as AppAccountRouteRouteImport } from './routes/_app/account/route'
import { Route as AppIncidentsIndexRouteImport } from './routes/_app/incidents/index'
import { Route as AppTeamSettingsRouteImport } from './routes/_app/team/settings'
import { Route as AppTeamMembersRouteImport } from './routes/_app/team/members'
import { Route as AppTeamInvitesRouteImport } from './routes/_app/team/invites'
import { Route as AppAccountSecurityRouteImport } from './routes/_app/account/security'
import { Route as AppAccountProfileRouteImport } from './routes/_app/account/profile'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyDashboardRoute = AppMyDashboardRouteImport.update({
  id: '/my-dashboard',
  path: '/my-dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDailyReportRoute = AppDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateTenantRoute = AppCreateTenantRouteImport.update({
  id: '/create-tenant',
  path: '/create-tenant',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamRouteRoute = AppTeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamSettingsRoute = AppTeamSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTeamRouteRoute,
} as any)
const AppTeamMembersRoute = AppTeamMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppTeamRouteRoute,
} as any)
const AppTeamInvitesRoute = AppTeamInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppTeamRouteRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRouteRouteWithChildren
  '/team': typeof AppTeamRouteRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/create-tenant': typeof AppCreateTenantRoute
  '/daily-report': typeof AppDailyReportRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-dashboard': typeof AppMyDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/schedule': typeof AppScheduleRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/team/invites': typeof AppTeamInvitesRoute
  '/team/members': typeof AppTeamMembersRoute
  '/team/settings': typeof AppTeamSettingsRoute
  '/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRouteRouteWithChildren
  '/team': typeof AppTeamRouteRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/create-tenant': typeof AppCreateTenantRoute
  '/daily-report': typeof AppDailyReportRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-dashboard': typeof AppMyDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/schedule': typeof AppScheduleRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/team/invites': typeof AppTeamInvitesRoute
  '/team/members': typeof AppTeamMembersRoute
  '/team/settings': typeof AppTeamSettingsRoute
  '/incidents': typeof AppIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/_app/account': typeof AppAccountRouteRouteWithChildren
  '/_app/team': typeof AppTeamRouteRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/create-tenant': typeof AppCreateTenantRoute
  '/_app/daily-report': typeof AppDailyReportRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/my-dashboard': typeof AppMyDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/account/profile': typeof AppAccountProfileRoute
  '/_app/account/security': typeof AppAccountSecurityRoute
  '/_app/team/invites': typeof AppTeamInvitesRoute
  '/_app/team/members': typeof AppTeamMembersRoute
  '/_app/team/settings': typeof AppTeamSettingsRoute
  '/_app/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/account'
    | '/team'
    | '/analytics'
    | '/create-tenant'
    | '/daily-report'
    | '/dashboard'
    | '/my-dashboard'
    | '/notifications'
    | '/schedule'
    | '/account/profile'
    | '/account/security'
    | '/team/invites'
    | '/team/members'
    | '/team/settings'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/account'
    | '/team'
    | '/analytics'
    | '/create-tenant'
    | '/daily-report'
    | '/dashboard'
    | '/my-dashboard'
    | '/notifications'
    | '/schedule'
    | '/account/profile'
    | '/account/security'
    | '/team/invites'
    | '/team/members'
    | '/team/settings'
    | '/incidents'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/_app/account'
    | '/_app/team'
    | '/_app/analytics'
    | '/_app/create-tenant'
    | '/_app/daily-report'
    | '/_app/dashboard'
    | '/_app/my-dashboard'
    | '/_app/notifications'
    | '/_app/schedule'
    | '/_app/account/profile'
    | '/_app/account/security'
    | '/_app/team/invites'
    | '/_app/team/members'
    | '/_app/team/settings'
    | '/_app/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-dashboard': {
      id: '/_app/my-dashboard'
      path: '/my-dashboard'
      fullPath: '/my-dashboard'
      preLoaderRoute: typeof AppMyDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/daily-report': {
      id: '/_app/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof AppDailyReportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/create-tenant': {
      id: '/_app/create-tenant'
      path: '/create-tenant'
      fullPath: '/create-tenant'
      preLoaderRoute: typeof AppCreateTenantRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/incidents/': {
      id: '/_app/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/team/settings': {
      id: '/_app/team/settings'
      path: '/settings'
      fullPath: '/team/settings'
      preLoaderRoute: typeof AppTeamSettingsRouteImport
      parentRoute: typeof AppTeamRouteRoute
    }
    '/_app/team/members': {
      id: '/_app/team/members'
      path: '/members'
      fullPath: '/team/members'
      preLoaderRoute: typeof AppTeamMembersRouteImport
      parentRoute: typeof AppTeamRouteRoute
    }
    '/_app/team/invites': {
      id: '/_app/team/invites'
      path: '/invites'
      fullPath: '/team/invites'
      preLoaderRoute: typeof AppTeamInvitesRouteImport
      parentRoute: typeof AppTeamRouteRoute
    }
    '/_app/account/security': {
      id: '/_app/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/account/profile': {
      id: '/_app/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
  }
}

interface AppAccountRouteRouteChildren {
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSecurityRoute: AppAccountSecurityRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppTeamRouteRouteChildren {
  AppTeamInvitesRoute: typeof AppTeamInvitesRoute
  AppTeamMembersRoute: typeof AppTeamMembersRoute
  AppTeamSettingsRoute: typeof AppTeamSettingsRoute
}

const AppTeamRouteRouteChildren: AppTeamRouteRouteChildren = {
  AppTeamInvitesRoute: AppTeamInvitesRoute,
  AppTeamMembersRoute: AppTeamMembersRoute,
  AppTeamSettingsRoute: AppTeamSettingsRoute,
}

const AppTeamRouteRouteWithChildren = AppTeamRouteRoute._addFileChildren(
  AppTeamRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppTeamRouteRoute: typeof AppTeamRouteRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCreateTenantRoute: typeof AppCreateTenantRoute
  AppDailyReportRoute: typeof AppDailyReportRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyDashboardRoute: typeof AppMyDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppTeamRouteRoute: AppTeamRouteRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCreateTenantRoute: AppCreateTenantRoute,
  AppDailyReportRoute: AppDailyReportRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMyDashboardRoute: AppMyDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
